### ISSUE TITLE
Error: AnimationNode is not defined

### ISSUE THREAD

**Issue by donmccurdy** [julienduroure/gltf2-blender-importer#1]
When importing files (including those without animation) I am seeing the error, `name 'AnimationNode' is not defined`.

<img width="914" alt="screen shot 2018-04-04 at 7 47 18 am" src="https://user-images.githubusercontent.com/1848368/38315069-854bb922-37dc-11e8-80f6-688229bbf745.png">

Tested on Duck and Avocado examples from http://github.com/KhronosGroup/glTF-Sample-Models.

**Comment by julienduroure** [comment]
Hello,

Seems I missed a file in my previous commit. Will be fixed very soon.
(I got your email, and I will answer soon)

**Comment by julienduroure** [comment]
Fixed !
Thanks for reporting

**Comment by donmccurdy** [comment]
Great, thank you!
