### ISSUE TITLE
Bones posing that doesn't start in bind position are not imported correctly.

### ISSUE THREAD

**Issue by slicer4ever** [julienduroure/gltf2-blender-importer#3]
If a bone's first pose frame is not the default bind position then importing doesn't properly capture that information.

**Comment by julienduroure** [comment]
Thanks for your bug report. I will check it in the following few days.

**Comment by julienduroure** [comment]
I tested with this file : 
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan

Rest pose is not same as 1rst frame, and impot is corectly done.

Can you please provide me a sample file, and how it was generated?

**Comment by julienduroure** [comment]
More than a month without any answer: closing this ticket.
If you have any more information, don't hesitate to comment and reopen it.
